ktor:
  application:
    modules:
      - io.github.krisalord.ApplicationKt.module
  deployment:
    port: 8080
  mongo:
    uri: ""
    database: "secure-media-api"
  jwt:
    secret: "super-long-random-secret-change-me"
    issuer: "secure-media"
    audience: "secure-media-users"
    validityMs: 86400000
  openai:
    apiKey: ""